In [2]:
import numpy as  np
import pandas as  pd
pd.set_option('display.max_columns',None)

In [3]:
Train_data= pd.read_csv(r'C:\Users\Lenovo\Desktop\dataset\train.csv',header=0,index_col=0)
Test_data= pd.read_csv(r'C:\Users\Lenovo\Desktop\dataset\test.csv',header=0,index_col=0)

In [4]:
print(Train_data.head())
print(Train_data.shape)

                                        track_name  popularity  acousticness  \
instance_id
MSC_83537.0                  Estrellitas y Duendes      49.178      0.970522
MSC_22044.0                               Al Norte      59.827      1.009380
MSC_62017.0       Yeah! (feat. Lil Jon & Ludacris)      89.023      0.020041
MSC_76365.0                          Canâ€™t You See      55.762      0.010284
MSC_71493.0  Sonata III (G Moll), BWV 1029: Adagio      45.095      0.858769

             danceability  duration_ms    energy  instrumentalness  \
instance_id
MSC_83537.0      0.580508   214625.776  0.192107          0.000000
MSC_22044.0      0.687542   216232.195  0.265942          0.000031
MSC_62017.0      0.967948   273314.723  0.857411          0.000000
MSC_76365.0      0.616287   189189.605  0.970513          0.000220
MSC_71493.0      0.280645   410136.987  0.114732          0.002753

                       key  liveness  loudness voice_gender   mode  \
instance_id
MSC_83537.0        Scale E  0.147134   -14.140          NaN  Major
MSC_22044.0        Scale A  0.174655   -13.716         Male      ?
MSC_62017.0        Scale D  0.042030    -4.995       Female  Major
MSC_76365.0        Scale D  0.124637    -4.262         Both  Major
MSC_71493.0  Scale F Sharp  0.134782   -26.922       Female  Minor

             speechiness               tempo musician_category   valence  \
instance_id
MSC_83537.0     0.046404  143.78799999999998              Band  0.598965
MSC_22044.0     0.039949                   ?              Band  0.357194
MSC_62017.0     0.119917  105.01799999999999              Band  0.635525
MSC_76365.0     0.167493                   ?              Duet  0.983750
MSC_71493.0     0.039139  112.18299999999999              Band  0.074412

            music_genre
instance_id
MSC_83537.0        Jazz
MSC_22044.0        Jazz
MSC_62017.0         Rap
MSC_76365.0        Rock
MSC_71493.0   Classical
(15681, 17)

In [5]:
Train_data.describe(include='all')

,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,voice_gender,mode,speechiness,tempo,musician_category,valence,music_genre
count,15681,15039.000000,15681.000000,15125.000000,1.558700e+04,15587.000000,15586.000000,15681,15681.000000,15645.000000,14916,15646,15655.000000,15681,14321,15004.000000,15681
unique,14799,NaN,NaN,NaN,NaN,NaN,NaN,12,NaN,NaN,3,3,NaN,12332,3,NaN,7
top,Smile,NaN,NaN,NaN,NaN,NaN,NaN,Scale C,NaN,NaN,Female,Major,NaN,?,Band,NaN,Classical
freq,7,NaN,NaN,NaN,NaN,NaN,NaN,1771,NaN,NaN,5050,9210,NaN,1476,4843,NaN,3990
mean,NaN,50.822720,0.446922,0.570106,2.480008e+05,0.426977,0.264290,NaN,0.194089,-11.621471,NaN,NaN,0.096411,NaN,NaN,0.451400,NaN
std,NaN,17.679789,0.416981,0.215045,1.568312e+05,0.514145,0.395788,NaN,0.160291,8.663364,NaN,NaN,0.105647,NaN,NaN,0.277220,NaN
min,NaN,0.000000,0.000002,0.063962,-1.000000e+00,-1.000000,0.000000,NaN,0.016652,-50.054000,NaN,NaN,0.023858,NaN,NaN,0.000000,NaN
25%,NaN,39.017000,0.044521,0.418635,1.860163e+05,0.158277,0.000000,NaN,0.101674,-15.504000,NaN,NaN,0.039549,NaN,NaN,0.212242,NaN
50%,NaN,54.109000,0.295272,0.586114,2.362127e+05,0.560389,0.000719,NaN,0.128784,-8.611000,NaN,NaN,0.050425,NaN,NaN,0.432478,NaN
75%,NaN,63.449000,0.929001,0.733073,2.975593e+05,0.791881,0.638930,NaN,0.228973,-5.715000,NaN,NaN,0.094230,NaN,NaN,0.665369,NaN
max,NaN,108.512000,1.094410,1.072089,3.410383e+06,1.094853,1.078601,NaN,1.080959,1.389000,NaN,NaN,1.000445,NaN,NaN,1.076971,NaN

In [6]:
Train_data=Train_data.replace('?',np.nan)

In [7]:
Train_data.describe(include='all')

,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,voice_gender,mode,speechiness,tempo,musician_category,valence,music_genre
count,15681,15039.000000,15681.000000,15125.000000,1.558700e+04,15587.000000,15586.000000,15681,15681.000000,15645.000000,14916,14567,15655.000000,14205,14321,15004.000000,15681
unique,14799,NaN,NaN,NaN,NaN,NaN,NaN,12,NaN,NaN,3,2,NaN,12331,3,NaN,7
top,Smile,NaN,NaN,NaN,NaN,NaN,NaN,Scale C,NaN,NaN,Female,Major,NaN,100.00299999999999,Band,NaN,Classical
freq,7,NaN,NaN,NaN,NaN,NaN,NaN,1771,NaN,NaN,5050,9210,NaN,6,4843,NaN,3990
mean,NaN,50.822720,0.446922,0.570106,2.480008e+05,0.426977,0.264290,NaN,0.194089,-11.621471,NaN,NaN,0.096411,NaN,NaN,0.451400,NaN
std,NaN,17.679789,0.416981,0.215045,1.568312e+05,0.514145,0.395788,NaN,0.160291,8.663364,NaN,NaN,0.105647,NaN,NaN,0.277220,NaN
min,NaN,0.000000,0.000002,0.063962,-1.000000e+00,-1.000000,0.000000,NaN,0.016652,-50.054000,NaN,NaN,0.023858,NaN,NaN,0.000000,NaN
25%,NaN,39.017000,0.044521,0.418635,1.860163e+05,0.158277,0.000000,NaN,0.101674,-15.504000,NaN,NaN,0.039549,NaN,NaN,0.212242,NaN
50%,NaN,54.109000,0.295272,0.586114,2.362127e+05,0.560389,0.000719,NaN,0.128784,-8.611000,NaN,NaN,0.050425,NaN,NaN,0.432478,NaN
75%,NaN,63.449000,0.929001,0.733073,2.975593e+05,0.791881,0.638930,NaN,0.228973,-5.715000,NaN,NaN,0.094230,NaN,NaN,0.665369,NaN
max,NaN,108.512000,1.094410,1.072089,3.410383e+06,1.094853,1.078601,NaN,1.080959,1.389000,NaN,NaN,1.000445,NaN,NaN,1.076971,NaN

In [8]:
#Preprocessing  Steps
# 1 )Feature importance- Removing 'track name ' from the variables
Train_data=Train_data.drop('track_name',axis=1)

In [9]:
#%%
Train_data.columns

Index(['popularity', 'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'key', 'liveness', 'loudness', 'voice_gender',
       'mode', 'speechiness', 'tempo', 'musician_category', 'valence',
       'music_genre'],
      dtype='object')

In [10]:
#%%
#2) Handling Missing values
Train_data.isnull().sum()

popularity            642
acousticness            0
danceability          556
duration_ms            94
energy                 94
instrumentalness       95
key                     0
liveness                0
loudness               36
voice_gender          765
mode                 1114
speechiness            26
tempo                1476
musician_category    1360
valence               677
music_genre             0
dtype: int64

In [11]:
print(Train_data.shape)
print(Train_data.dtypes)

(15681, 16)
popularity           float64
acousticness         float64
danceability         float64
duration_ms          float64
energy               float64
instrumentalness     float64
key                   object
liveness             float64
loudness             float64
voice_gender          object
mode                  object
speechiness          float64
tempo                 object
musician_category     object
valence              float64
music_genre           object
dtype: object

In [12]:
Train_data['tempo']=Train_data['tempo'].astype(float,errors='raise')

In [13]:
Train_data.dtypes

popularity           float64
acousticness         float64
danceability         float64
duration_ms          float64
energy               float64
instrumentalness     float64
key                   object
liveness             float64
loudness             float64
voice_gender          object
mode                  object
speechiness          float64
tempo                float64
musician_category     object
valence              float64
music_genre           object
dtype: object

In [14]:
#Replacing missing values with mean value  in continuous variables.
for i in['popularity','danceability','duration_ms','energy','instrumentalness','loudness','speechiness','tempo','valence']:
    Train_data[i].fillna(Train_data[i].mean(),inplace= True)

In [15]:
 Train_data.isnull().sum()

popularity              0
acousticness            0
danceability            0
duration_ms             0
energy                  0
instrumentalness        0
key                     0
liveness                0
loudness                0
voice_gender          765
mode                 1114
speechiness             0
tempo                   0
musician_category    1360
valence                 0
music_genre             0
dtype: int64

In [16]:
 #Replacing missing values with mode value  in categorical variables.
 for i in ['voice_gender','mode','musician_category']:
     Train_data[i].fillna(Train_data[i].mode()[0],inplace= True)

In [17]:
 Train_data.isnull().sum()

popularity           0
acousticness         0
danceability         0
duration_ms          0
energy               0
instrumentalness     0
key                  0
liveness             0
loudness             0
voice_gender         0
mode                 0
speechiness          0
tempo                0
musician_category    0
valence              0
music_genre          0
dtype: int64

In [18]:
 Train_data.describe(include='all')

,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,voice_gender,mode,speechiness,tempo,musician_category,valence,music_genre
count,15681.000000,15681.000000,15681.000000,1.568100e+04,15681.000000,15681.000000,15681,15681.000000,15681.000000,15681,15681,15681.000000,15681.000000,15681,15681.000000,15681
unique,NaN,NaN,NaN,NaN,NaN,NaN,12,NaN,NaN,3,2,NaN,NaN,3,NaN,7
top,NaN,NaN,NaN,NaN,NaN,NaN,Scale C,NaN,NaN,Female,Major,NaN,NaN,Band,NaN,Classical
freq,NaN,NaN,NaN,NaN,NaN,NaN,1771,NaN,NaN,5815,10324,NaN,NaN,6203,NaN,3990
mean,50.822720,0.446922,0.570106,2.480008e+05,0.426977,0.264290,NaN,0.194089,-11.621471,NaN,NaN,0.096411,115.447641,NaN,0.451400,NaN
std,17.314066,0.416981,0.211198,1.563604e+05,0.512602,0.394587,NaN,0.160291,8.653413,NaN,NaN,0.105559,29.121195,NaN,0.271169,NaN
min,0.000000,0.000002,0.063962,-1.000000e+00,-1.000000,0.000000,NaN,0.016652,-50.054000,NaN,NaN,0.023858,34.347000,NaN,0.000000,NaN
25%,39.414000,0.044521,0.425694,1.864208e+05,0.159934,0.000000,NaN,0.101674,-15.478000,NaN,NaN,0.039563,92.427000,NaN,0.222389,NaN
50%,53.135000,0.295272,0.576149,2.368236e+05,0.557718,0.000801,NaN,0.128784,-8.627000,NaN,NaN,0.050502,115.447641,NaN,0.451400,NaN
75%,63.064000,0.929001,0.726697,2.969948e+05,0.790423,0.632455,NaN,0.228973,-5.724000,NaN,NaN,0.094725,134.163000,NaN,0.652638,NaN
max,108.512000,1.094410,1.072089,3.410383e+06,1.094853,1.078601,NaN,1.080959,1.389000,NaN,NaN,1.000445,219.331000,NaN,1.076971,NaN

In [19]:
 #3)Converting categorical data into numerical data
 Train_data.music_genre .value_counts()

Classical     3990
Rock          3879
Rap           3207
Jazz          2850
Country        683
Electronic     614
Hip-Hop        458
Name: music_genre, dtype: int64

In [20]:
Train_data.music_genre=Train_data.music_genre.map({'Classical':1,'Rock':2,'Rap':3,'Jazz':4,'Country':5,'Electronic':6,'Hip-Hop':7})

In [21]:
 Train_data.music_genre.value_counts()

1    3990
2    3879
3    3207
4    2850
5     683
6     614
7     458
Name: music_genre, dtype: int64

In [22]:
colname=['key','voice_gender','mode','musician_category']
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for i in colname:
    Train_data[i]=le.fit_transform(Train_data[i])

In [23]:
Train_data.head()

,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,voice_gender,mode,speechiness,tempo,musician_category,valence,music_genre
instance_id,,,,,,,,,,,,,,,,
MSC_83537.0,49.178,0.970522,0.580508,214625.776,0.192107,0.000000,7,0.147134,-14.140,1,0,0.046404,143.788000,0,0.598965,4
MSC_22044.0,59.827,1.009380,0.687542,216232.195,0.265942,0.000031,0,0.174655,-13.716,2,0,0.039949,115.447641,0,0.357194,4
MSC_62017.0,89.023,0.020041,0.967948,273314.723,0.857411,0.000000,5,0.042030,-4.995,1,0,0.119917,105.018000,0,0.635525,3
MSC_76365.0,55.762,0.010284,0.616287,189189.605,0.970513,0.000220,5,0.124637,-4.262,0,0,0.167493,115.447641,1,0.983750,2
MSC_71493.0,45.095,0.858769,0.280645,410136.987,0.114732,0.002753,9,0.134782,-26.922,1,1,0.039139,112.183000,0,0.074412,1

In [24]:
 #Preprocessing  Testing data
print(Test_data.head())
print(Test_data.shape)

                                              track_name  popularity  \
instance_id
MSC_70753.0  Bard, a Man of Lake-town - Extended Version      26.101
MSC_24064.0                                    New Kings      66.325
MSC_22731.0                                Silver Lining      71.871
MSC_32095.0                     A Tale That Wasn't Right      56.151
MSC_24198.0                                    Get Ready      43.687

             acousticness  danceability  duration_ms    energy  \
instance_id
MSC_70753.0      0.823765      0.115490   211462.287  0.125325
MSC_24064.0      0.015441      0.592838   249151.238  0.870798
MSC_22731.0      0.001006      0.510340   215693.240  0.683077
MSC_32095.0      0.315650      0.338336   307056.179  0.608904
MSC_24198.0      0.038336      0.773904   352802.872  0.955500

             instrumentalness            key  liveness  loudness voice_gender  \
instance_id
MSC_70753.0          0.945272  Scale A Sharp  0.120392   -25.541         Both
MSC_24064.0          0.000108        Scale E  0.406722    -3.905         Male
MSC_22731.0          0.000000        Scale C  0.084608    -6.825       Female
MSC_32095.0          0.000000        Scale A  0.276811    -8.382       Female
MSC_24198.0          0.000007        Scale D  0.301726    -4.733         Both

              mode  speechiness              tempo musician_category   valence
instance_id
MSC_70753.0  Minor     0.038657             80.777              Duet  0.041238
MSC_24064.0      ?     0.051368  76.00399999999999              Band  0.456309
MSC_22731.0  Major     0.034303            144.458              Solo  0.193332
MSC_32095.0  Minor     0.036934            118.145              Solo  0.214906
MSC_24198.0  Major     0.079688             95.012              Duet  0.757347
(3921, 16)

In [25]:
Test_data=Test_data.replace('?',np.nan)

In [26]:
Test_data.describe(include='all')

,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,voice_gender,mode,speechiness,tempo,musician_category,valence
count,3921,3755.000000,3921.000000,3782.000000,3.900000e+03,3888.000000,3898.000000,3921,3921.000000,3918.000000,3735,3662,3914.000000,3530,3609,3730.000000
unique,3850,NaN,NaN,NaN,NaN,NaN,NaN,12,NaN,NaN,3,2,NaN,3400,3,NaN
top,Psycho,NaN,NaN,NaN,NaN,NaN,NaN,Scale C,NaN,NaN,Both,Major,NaN,129.983,Duet,NaN
freq,3,NaN,NaN,NaN,NaN,NaN,NaN,433,NaN,NaN,1306,2342,NaN,3,1262,NaN
mean,NaN,50.581611,0.445990,0.569210,2.495970e+05,0.429010,0.265753,NaN,0.193124,-11.342702,NaN,NaN,0.097000,NaN,NaN,0.450862
std,NaN,18.354740,0.417772,0.215494,1.556545e+05,0.510612,0.394520,NaN,0.159287,8.403444,NaN,NaN,0.107789,NaN,NaN,0.275487
min,NaN,0.000000,0.000002,0.065425,-1.000000e+00,-1.000000,0.000000,NaN,0.026103,-48.690000,NaN,NaN,0.024054,NaN,NaN,0.026831
25%,NaN,38.762500,0.041812,0.411890,1.873481e+05,0.172121,0.000000,NaN,0.101034,-15.168500,NaN,NaN,0.039443,NaN,NaN,0.215056
50%,NaN,54.310000,0.282626,0.585554,2.387812e+05,0.564615,0.000808,NaN,0.126396,-8.593500,NaN,NaN,0.050367,NaN,NaN,0.430556
75%,NaN,63.583500,0.926555,0.737308,3.006447e+05,0.790241,0.635487,NaN,0.226578,-5.636750,NaN,NaN,0.092670,NaN,NaN,0.672546
max,NaN,100.350000,1.093955,1.056572,2.096423e+06,1.092213,1.066941,NaN,1.057769,0.631000,NaN,NaN,0.963375,NaN,NaN,1.068861

In [27]:
#Preprocessing  Steps
# 1 )Feature importance- Removing 'track name ' from the variables
Test_data=Test_data.drop('track_name',axis=1)

In [28]:
Test_data.columns

Index(['popularity', 'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'key', 'liveness', 'loudness', 'voice_gender',
       'mode', 'speechiness', 'tempo', 'musician_category', 'valence'],
      dtype='object')

In [29]:
#2) Handling Missing values
Test_data.isnull().sum()

popularity           166
acousticness           0
danceability         139
duration_ms           21
energy                33
instrumentalness      23
key                    0
liveness               0
loudness               3
voice_gender         186
mode                 259
speechiness            7
tempo                391
musician_category    312
valence              191
dtype: int64

In [30]:
print(Test_data.shape)
print(Test_data.dtypes)

(3921, 15)
popularity           float64
acousticness         float64
danceability         float64
duration_ms          float64
energy               float64
instrumentalness     float64
key                   object
liveness             float64
loudness             float64
voice_gender          object
mode                  object
speechiness          float64
tempo                 object
musician_category     object
valence              float64
dtype: object

In [31]:
Test_data['tempo']=Test_data['tempo'].astype(float,errors='raise')

In [32]:
Test_data.dtypes

popularity           float64
acousticness         float64
danceability         float64
duration_ms          float64
energy               float64
instrumentalness     float64
key                   object
liveness             float64
loudness             float64
voice_gender          object
mode                  object
speechiness          float64
tempo                float64
musician_category     object
valence              float64
dtype: object

In [33]:
#Replacing missing values with mean value  in continuous variables.
for i in['popularity','danceability','duration_ms','energy','instrumentalness','loudness','speechiness','tempo','valence']:
    Test_data[i].fillna(Test_data[i].mean(),inplace= True)

In [34]:
Test_data.isnull().sum()

popularity             0
acousticness           0
danceability           0
duration_ms            0
energy                 0
instrumentalness       0
key                    0
liveness               0
loudness               0
voice_gender         186
mode                 259
speechiness            0
tempo                  0
musician_category    312
valence                0
dtype: int64

In [35]:
 #Replacing missing values with mode value  in categorical variables.
 for i in ['voice_gender','mode','musician_category']:
     Test_data[i].fillna(Test_data[i].mode()[0],inplace= True)

In [36]:
Test_data.isnull().sum()

popularity           0
acousticness         0
danceability         0
duration_ms          0
energy               0
instrumentalness     0
key                  0
liveness             0
loudness             0
voice_gender         0
mode                 0
speechiness          0
tempo                0
musician_category    0
valence              0
dtype: int64

In [37]:
 Test_data.describe(include='all')

,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,voice_gender,mode,speechiness,tempo,musician_category,valence
count,3921.000000,3921.000000,3921.000000,3.921000e+03,3921.000000,3921.000000,3921,3921.000000,3921.000000,3921,3921,3921.000000,3921.000000,3921,3921.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,12,NaN,NaN,3,2,NaN,NaN,3,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,Scale C,NaN,NaN,Both,Major,NaN,NaN,Duet,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,433,NaN,NaN,1492,2601,NaN,NaN,1574,NaN
mean,50.581611,0.445990,0.569210,2.495970e+05,0.429010,0.265753,NaN,0.193124,-11.342702,NaN,NaN,0.097000,116.111768,NaN,0.450862
std,17.961902,0.417772,0.211639,1.552370e+05,0.508459,0.393361,NaN,0.159287,8.400228,NaN,NaN,0.107693,29.259239,NaN,0.268691
min,0.000000,0.000002,0.065425,-1.000000e+00,-1.000000,0.000000,NaN,0.026103,-48.690000,NaN,NaN,0.024054,44.974000,NaN,0.026831
25%,39.292000,0.041812,0.420225,1.877879e+05,0.173747,0.000000,NaN,0.101034,-15.167000,NaN,NaN,0.039445,93.980000,NaN,0.226293
50%,53.157000,0.282626,0.574001,2.394281e+05,0.558540,0.000895,NaN,0.126396,-8.599000,NaN,NaN,0.050404,116.111768,NaN,0.449229
75%,63.240000,0.926555,0.732661,2.998095e+05,0.788563,0.626258,NaN,0.226578,-5.639000,NaN,NaN,0.094051,135.061000,NaN,0.659254
max,100.350000,1.093955,1.056572,2.096423e+06,1.092213,1.066941,NaN,1.057769,0.631000,NaN,NaN,0.963375,211.261000,NaN,1.068861

In [38]:
#3)Converting categorical data into numerical data
colname=['key','voice_gender','mode','musician_category']
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for i in colname:
    Test_data[i]=le.fit_transform(Test_data[i])

In [39]:
#4)Training and Testing data 
  #Training data
X_train=Train_data.values[:,0:-1]
Y_train=Train_data.values[:,-1]
Y_train=Y_train.astype(int)

In [40]:
Y_train.shape

(15681,)

In [41]:
#Testing data
X_test=Test_data.values[:,:]

In [42]:
X_test.shape

(3921, 15)

In [43]:
#4)Scaling the Xdata for Training and Testing
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)
X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)

In [45]:

pip install imblearn

Requirement already satisfied: imblearn in c:\users\lenovo\anaconda3\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\lenovo\anaconda3\lib\site-packages (from imblearn) (0.7.0)
Requirement already satisfied: numpy>=1.13.3 in c:\users\lenovo\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.19.3)
Requirement already satisfied: scikit-learn>=0.23 in c:\users\lenovo\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (0.24.0)
Requirement already satisfied: joblib>=0.11 in c:\users\lenovo\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (0.13.2)
Requirement already satisfied: scipy>=0.19.1 in c:\users\lenovo\appdata\roaming\python\python37\site-packages (from imbalanced-learn->imblearn) (1.5.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn>=0.23->imbalanced-learn->imblearn) (2.1.0)
Note: you may need to restart the kernel to use updated packages.

In [46]:

# Balancing data set
from imblearn.over_sampling import SMOTE
smote=SMOTE()

In [47]:
X_train_smote,Y_train_smote=smote.fit_sample(X_train.astype(float),Y_train)

In [48]:
from collections import Counter

In [ ]:
print('before smote',Counter(Y_train))
print('after smaote',Counter(Y_train_smote))

In [49]:
#Using KNN method
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=10,metric='manhattan')
model_KNN.fit(X_train_smote,Y_train_smote)
Y_pred=model_KNN.predict(X_test)

In [50]:
model_KNN.score(X_train_smote,Y_train_smote)

0.8140708915145005

In [51]:
# Using SVM
from sklearn.svm import SVC
svc_model=SVC(kernel='rbf',C=600.0,gamma=0.1)
svc_model.fit(X_train_smote, Y_train_smote)
Y_pred=svc_model.predict(X_test)

In [52]:
svc_model.score(X_train_smote,Y_train_smote)

0.9972789115646259

In [53]:
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100, random_state=10)
model_RandomForest.fit(X_train_smote,Y_train_smote)

Y_pred=model_RandomForest.predict(X_test)

In [54]:
model_RandomForest.score(X_train_smote,Y_train_smote)

1.0

In [55]:
Test_data_1=pd.read_csv(r'C:\Users\Lenovo\Desktop\dataset\test.csv',header=0,index_col=0)
Test_data_1["music_genre"]=Y_pred
Test_data_1.head()

,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,voice_gender,mode,speechiness,tempo,musician_category,valence,music_genre
instance_id,,,,,,,,,,,,,,,,,
MSC_70753.0,"Bard, a Man of Lake-town - Extended Version",26.101,0.823765,0.115490,211462.287,0.125325,0.945272,Scale A Sharp,0.120392,-25.541,Both,Minor,0.038657,80.777,Duet,0.041238,1
MSC_24064.0,New Kings,66.325,0.015441,0.592838,249151.238,0.870798,0.000108,Scale E,0.406722,-3.905,Male,?,0.051368,76.00399999999999,Band,0.456309,2
MSC_22731.0,Silver Lining,71.871,0.001006,0.510340,215693.240,0.683077,0.000000,Scale C,0.084608,-6.825,Female,Major,0.034303,144.458,Solo,0.193332,2
MSC_32095.0,A Tale That Wasn't Right,56.151,0.315650,0.338336,307056.179,0.608904,0.000000,Scale A,0.276811,-8.382,Female,Minor,0.036934,118.145,Solo,0.214906,2
MSC_24198.0,Get Ready,43.687,0.038336,0.773904,352802.872,0.955500,0.000007,Scale D,0.301726,-4.733,Both,Major,0.079688,95.012,Duet,0.757347,4

In [56]:
Test_data_1.columns

Index(['track_name', 'popularity', 'acousticness', 'danceability',
       'duration_ms', 'energy', 'instrumentalness', 'key', 'liveness',
       'loudness', 'voice_gender', 'mode', 'speechiness', 'tempo',
       'musician_category', 'valence', 'music_genre'],
      dtype='object')

In [57]:
Test_data_1= Test_data_1.drop(['track_name', 'popularity', 'acousticness',
       'danceability', 'duration_ms', 'energy', 'instrumentalness', 'key',
       'liveness', 'loudness', 'voice_gender', 'mode', 'speechiness', 'tempo',
       'musician_category', 'valence'],axis=1)

In [58]:
Test_data_1.head()

             music_genre
instance_id
MSC_70753.0            1
MSC_24064.0            2
MSC_22731.0            2
MSC_32095.0            2
MSC_24198.0            4

In [59]:
Test_data_1=Test_data_1.music_genre.map({1:'Classical',2:'Rock',3:'Rap',4:'Jazz',5:'Country',6:'Electronic',7:'Hip-Hop'})

In [60]:
Test_data_1.value_counts()

Rock          996
Classical     989
Rap           787
Jazz          678
Country       219
Electronic    183
Hip-Hop        69
Name: music_genre, dtype: int64

In [61]:
Test_data_1.to_csv(r'C:\Users\Lenovo\Desktop\dataset\music_genere_RF_NEW.csv')